### ISSUE TITLE
How to build backend as a monolithic service?

### ISSUE THREAD

**Issue by digrich** [fastify/fastify-example-twitter#28]
I am getting the following exception while building the backend. Am I missing something?

I did,

npm install
npm start -- --log-level trace --port 3001

> server@1.0.0 start /Users/digvijay/tools/fastify-example-twitter/fastify-example-twitter
> env-cmd local.env fastify start index.js "--log-level" "trace" "--port" "3001"

mongodb://localhost:27017/twitter
assert.js:669
assert.ifError = function ifError(err) { if (err) throw err; };
                                                  ^

MongoError: unknown option to collMod: validator
    at /Users/digvijay/tools/fastify-example-twitter/fastify-example-twitter/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/Users/digvijay/tools/fastify-example-twitter/fastify-example-twitter/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/Users/digvijay/tools/fastify-example-twitter/fastify-example-twitter/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/Users/digvijay/tools/fastify-example-twitter/fastify-example-twitter/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/Users/digvijay/tools/fastify-example-twitter/fastify-example-twitter/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 start: `env-cmd local.env fastify start index.js "--log-level" "trace" "--port" "3001"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/digvijay/.npm/_logs/2019-01-31T22_40_15_559Z-debug.log

**Comment by digrich** [comment]
After upgrading to latest mongodb, it resolved. Closing it.
